Homework 6
SergeySalimov/FD2-Homework pull request #8
Opened 2020-01-21 19:49 UTC by SergeySalimov

Привет
сделана Rest функция-конструктор на прототипах со всеми CRUD операциями, сделал UI для проверки ее работы, постарался максимально отрефакторить код.

2020-01-28 18:48 UTC, doroshkovd requested changes
Напиши 'use strict' в начале своих файлов, попробуй сам разобраться в чем проблема)

2020-01-28 18:48 UTC, doroshkovd commented on HW6/public_html/js/rest.js
> +Rest.prototype.get = function (url, fnOnLoad = () => this.restResponse, whatToGet = '/product') {
whatToGet не совсем норм название например resource, segment, route

2020-01-29 10:44 UTC, SergeySalimov commented
Привет
Исправил ситуацию:
1. Конструктор Rest принимает функцию, которая срабатывает по окончанию работы асинхронной части и принимает в себя в качестве аргумента результат работы асинхронной функции.
2. Переделал работу отработки окончания работы асинхронного запроса на сервер. Мне кажется, даже упростилось все: 
- не понадобился Observer
- сообщения все стали в одной переменной
- убрал функцию генерации ID, мы его получаем из ответа
- кода стало меньше и он стал понятнее для прочтения

2020-01-29 10:47 UTC, SergeySalimov commented on HW6/public_html/js/rest.js
> +Rest.prototype.get = function (url, fnOnLoad = () => this.restResponse, whatToGet = '/product') {
Исправил

2020-02-04 17:53 UTC, doroshkovd approved these changes

2020-02-04 18:49 UTC, merged